# Generated by Django 2.0.5 on 2018-07-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='selected',
            field=models.BooleanField(default=True, verbose_name='是否选择'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='商品'),
        ),
    ]
