# Generated by Django 2.0.5 on 2018-07-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='note',
            field=models.CharField(default='', max_length=200, verbose_name='备注'),
        ),
    ]
