# Generated by Django 2.0.5 on 2018-07-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180731_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_mount',
            new_name='order_amount',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='商品'),
        ),
    ]
