# Generated by Django 2.0.5 on 2018-07-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180731_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
    ]
