# Generated by Django 2.0.5 on 2018-08-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180801_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_RECEIVED', '待收货'), ('WAIT_COMMENT', '带评价'), ('AFTER_SALE', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('WAIT_PAY', '待付款')], default='paying', max_length=20, verbose_name='订单状态'),
        ),
    ]
