# Generated by Django 2.0.5 on 2018-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180702_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
